In [1]:
import pandas as pd

In [2]:
dict = {'col1' : [1,2,3,4,5],
        'col2' : [42,32,43,25,64],
        'col3' : ['sudhanshu','krish','blah','ineuron','DS'],
        }

In [3]:
df = pd.DataFrame(dict )

In [4]:
df

col1  col2       col3
0     1    42  sudhanshu
1     2    32      krish
2     3    43       blah
3     4    25    ineuron
4     5    64         DS

In [5]:
df['col4'] = df['col1']**2

In [6]:
df

col1  col2       col3  col4
0     1    42  sudhanshu     1
1     2    32      krish     4
2     3    43       blah     9
3     4    25    ineuron    16
4     5    64         DS    25

In [7]:
df['col5'] = df['col3'].str[0]

In [8]:
df

col1  col2       col3  col4 col5
0     1    42  sudhanshu     1    s
1     2    32      krish     4    k
2     3    43       blah     9    b
3     4    25    ineuron    16    i
4     5    64         DS    25    D

In [9]:
def test(x) : 
    if 's' in x :  return 's'
    else : return 'z'


In [10]:
# this checks not for whole string as 's' but any one occurence of 's' in x
def test1(x) : 
    if x=='s' :  return 's'
    else : return 'z'

In [11]:
df['col3_3'] = df['col3'].apply(test)

In [12]:
df

col1  col2       col3  col4 col5 col3_3
0     1    42  sudhanshu     1    s      s
1     2    32      krish     4    k      s
2     3    43       blah     9    b      z
3     4    25    ineuron    16    i      z
4     5    64         DS    25    D      z

In [13]:
df.drop('col3_3',inplace=True,axis=1)

In [14]:
df

col1  col2       col3  col4 col5
0     1    42  sudhanshu     1    s
1     2    32      krish     4    k
2     3    43       blah     9    b
3     4    25    ineuron    16    i
4     5    64         DS    25    D

In [15]:
df['col6'] = df['col5'].apply(lambda x : 's' if x == 's' else 'z')

In [16]:
df

col1  col2       col3  col4 col5 col6
0     1    42  sudhanshu     1    s    s
1     2    32      krish     4    k    z
2     3    43       blah     9    b    z
3     4    25    ineuron    16    i    z
4     5    64         DS    25    D    z

In [17]:
df.drop('col6',inplace=True,axis=1)

In [18]:
df

col1  col2       col3  col4 col5
0     1    42  sudhanshu     1    s
1     2    32      krish     4    k
2     3    43       blah     9    b
3     4    25    ineuron    16    i
4     5    64         DS    25    D

In [19]:
df['col7'] = df['col3'].apply(len)

In [20]:
df

col1  col2       col3  col4 col5  col7
0     1    42  sudhanshu     1    s     9
1     2    32      krish     4    k     5
2     3    43       blah     9    b     4
3     4    25    ineuron    16    i     7
4     5    64         DS    25    D     2

In [21]:
import math
df['col8'] = df['col2'].apply(math.log)

In [22]:
df

col1  col2       col3  col4 col5  col7      col8
0     1    42  sudhanshu     1    s     9  3.737670
1     2    32      krish     4    k     5  3.465736
2     3    43       blah     9    b     4  3.761200
3     4    25    ineuron    16    i     7  3.218876
4     5    64         DS    25    D     2  4.158883

In [23]:
import numpy as np

In [24]:
l = ['som',1,3,4,5]

In [25]:
np.array(l)

array(['som', '1', '3', '4', '5'], dtype='<U11')

In [26]:
type(np.array(l))

numpy.ndarray

In [27]:
# upcasting 
np.array([3,4,5,2.0])

array([3., 4., 5., 2.])

In [28]:
a = np.array([[2,4],[3,6]])

In [29]:
a

array([[2, 4],
       [3, 6]])

In [30]:
a[1]

array([3, 6])

In [31]:
a[1][1]

6

In [32]:
a2 = np.array([1,2,3,4],ndmin=4)

In [33]:
a2

array([[[[1, 2, 3, 4]]]])

In [34]:
a2[0][0][0][0]

1

In [35]:
np.asarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [36]:
np.asanyarray([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [37]:
np.mat([1,2,3,4,5])

matrix([[1, 2, 3, 4, 5]])

In [38]:
a3 = np.mat([1,2,3,4,5])

In [39]:
# converted matrix to array
np.asarray(a3)

array([[1, 2, 3, 4, 5]])

In [40]:
# did not convert matrix to array
np.asanyarray(a3)

matrix([[1, 2, 3, 4, 5]])

In [41]:
np.fromfunction(lambda i,j: ((i+1)%3)==0 , (3,3) )
# this shows that row wise iterations are done on a column then on another column and so on.

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [42]:
np.fromfunction(lambda i,j: i*j , (4,4) )

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [43]:
# by default it gives floating point number, however, you can define dtype on your own.
np.fromfunction(lambda i,j: i*j , (4,4),dtype = int )

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [44]:
np.fromfunction(lambda i,j,z: i*j*z , (3,3,1),dtype = int )
# (3,3,1) -> 3 arrays of 3 X 1(3 rows, 1 column)

array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]])

In [45]:
# only 'i' in array elements
np.fromfunction(lambda i,j,z: i , (3,3,3),dtype = int )

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [46]:
# only j in array elements 
np.fromfunction(lambda i,j,z: j, (3,3,3),dtype = int )

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]])

In [47]:
# (3,3,2)
# (depth,rows,columns)

In [48]:
# You can't visualize this
# but, always read from back
# Here, there is a bundle of 3 arrays of 2 X 2 arrays 
# and there are 4 such bundles
np.fromfunction(lambda i,j,z,p : i*j*z*p,(4,3,2,2),dtype=int)

array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 1]],

        [[0, 0],
         [0, 2]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 2]],

        [[0, 0],
         [0, 4]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 3]],

        [[0, 0],
         [0, 6]]]])

In [49]:
a = np.fromfunction(lambda i,j,z : i*j*z,(4,3,2),dtype=int)

In [50]:
a.ndim

3

In [51]:
a.size

24

In [52]:
a.shape

(4, 3, 2)

In [53]:
a.dtype

dtype('int32')

In [54]:
# will give error because you can't create df from 3d data, you will have to either do flattening or provide 2d input.
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [ ]:
a = np.fromfunction(lambda i,j : i*j,(400,100),dtype=int)

In [ ]:
a

In [55]:
pd.DataFrame(a)

ValueError: Must pass 2-d input. shape=(4, 3, 2)

In [56]:
# this function will be used a lot
np.random.rand(100,4)
# generates random values in the given shape

array([[0.88879374, 0.25543565, 0.87985202, 0.68851603],
       [0.02185131, 0.22246379, 0.91218546, 0.12818246],
       [0.59812812, 0.02856559, 0.15389029, 0.40688748],
       [0.22916802, 0.69463995, 0.01472305, 0.43087275],
       [0.43129287, 0.65780948, 0.80438798, 0.59573789],
       [0.20308779, 0.57586085, 0.66424091, 0.08506964],
       [0.48696502, 0.5654013 , 0.21191622, 0.17629537],
       [0.50569539, 0.13632195, 0.56081505, 0.14113813],
       [0.90537564, 0.76349619, 0.27411039, 0.24222451],
       [0.23962123, 0.50475442, 0.79494977, 0.82735287],
       [0.570746  , 0.75757707, 0.40036798, 0.22117985],
       [0.17100552, 0.78624976, 0.13351739, 0.81113161],
       [0.9014834 , 0.18904252, 0.40024077, 0.74311429],
       [0.89715769, 0.72973346, 0.97025643, 0.79980509],
       [0.97954849, 0.91202921, 0.8887066 , 0.53634524],
       [0.46662024, 0.90302737, 0.30712679, 0.34664326],
       [0.85085992, 0.14853303, 0.36432056, 0.83265869],
       [0.86939725, 0.15389751,

In [57]:
np.random.randint(4,50)
# generates random number between the entered range

5

In [58]:
np.random.randn(4,5)
# random numbers in 4 rows, 5 columns 

# Generats nornmally distributed values, average of all these values will be zero. 
# standard deviation will be 1


array([[-0.52760286, -0.16295154,  1.44017354,  1.28001264,  0.60350577],
       [ 2.01601527,  0.06952598,  0.92718295,  1.36225928,  2.3623366 ],
       [-0.21356406, -0.60343705, -0.08705359, -0.21229997,  2.0514034 ],
       [-1.60462241, -0.04588997,  0.8638666 , -0.06063537,  0.57821681]])

In [59]:
pd.DataFrame(np.random.randn(4,5))

0         1         2         3         4
0  1.083646 -0.049761 -1.054334 -0.345087 -0.273952
1 -2.668407 -1.300719 -0.759283  0.894456 -0.153274
2 -1.018197 -0.839665 -0.413190  0.540081  1.483781
3 -0.320179  2.190380 -0.616700 -0.368334  0.808048

In [60]:
# converting 3 dimensional data to 2d data

In [61]:
a = np.fromfunction(lambda i,j,z : i*j*z,(4,3,2),dtype=int)
# 24 elements


In [63]:
# You have to give dimensions in such a way that number of elements are same for previous and new dimensions.
a.reshape(12,2)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [0, 2],
       [0, 0],
       [0, 2],
       [0, 4],
       [0, 0],
       [0, 3],
       [0, 6]])

In [64]:
a.reshape(6,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 2],
       [0, 0, 0, 2],
       [0, 4, 0, 0],
       [0, 3, 0, 6]])

In [65]:
a.reshape(1,24)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 2, 0, 4, 0, 0, 0, 3,
        0, 6]])

In [67]:
pd.DataFrame(a.reshape(3,8))

0  1  2  3  4  5  6  7
0  0  0  0  0  0  0  0  0
1  0  1  0  2  0  0  0  2
2  0  4  0  0  0  3  0  6

In [68]:
## you can give any number of dimensions, only the number of elements must be same.
a.reshape(4,2,1,3)

array([[[[0, 0, 0]],

        [[0, 0, 0]]],


       [[[0, 0, 0]],

        [[1, 0, 2]]],


       [[[0, 0, 0]],

        [[2, 0, 4]]],


       [[[0, 0, 0]],

        [[3, 0, 6]]]])

In [72]:
a.reshape(1,4,2,1,3,1)

array([[[[[[0],
           [0],
           [0]]],


         [[[0],
           [0],
           [0]]]],



        [[[[0],
           [0],
           [0]]],


         [[[1],
           [0],
           [2]]]],



        [[[[0],
           [0],
           [0]]],


         [[[2],
           [0],
           [4]]]],



        [[[[0],
           [0],
           [0]]],


         [[[3],
           [0],
           [6]]]]]])

In [79]:
# -ve number means dimension will be automatically filled
# any -ve number will work
a.reshape(4,-123452345)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 2],
       [0, 0, 0, 2, 0, 4],
       [0, 0, 0, 3, 0, 6]])

In [77]:
a.reshape(5,-12345345)

ValueError: cannot reshape array of size 24 into shape (5,newaxis)

In [80]:
a.reshape(2,4,-5432)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [1, 0, 2]],

       [[0, 0, 0],
        [2, 0, 4],
        [0, 0, 0],
        [3, 0, 6]]])

In [81]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [82]:
list(range(4,10,2))

[4, 6, 8]

In [83]:
# inbuilt range function only takes integer as step size,lower bound and upper bound.
list(range(4,10,0.2))

TypeError: 'float' object cannot be interpreted as an integer

In [86]:
list(range(4,10.5,2))

TypeError: 'float' object cannot be interpreted as an integer

In [84]:
# numpy has a equivalent function to range
# np.arange() can take float as a step size, and even lower and upper bounds.
np.arange(4,10,0.2)

array([4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4,
       6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. ,
       9.2, 9.4, 9.6, 9.8])

In [89]:
np.arange(4,10.5,0.2)

array([ 4. ,  4.2,  4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,
        6.2,  6.4,  6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,
        8.4,  8.6,  8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4])

In [92]:
a1 = np.arange(4,10.5,0.2)


In [91]:
# You can use slicing operator on numpy.arrays too
a1[0:5]

array([4. , 4.2, 4.4, 4.6, 4.8])

In [93]:
arr = np.random.rand(4,5)

In [94]:
arr

array([[0.65606435, 0.67818371, 0.44047451, 0.15464058, 0.5904563 ],
       [0.1836203 , 0.73470839, 0.80892093, 0.98021567, 0.72487239],
       [0.57043771, 0.55017421, 0.46563048, 0.79097872, 0.11013741],
       [0.52457782, 0.61419716, 0.73371306, 0.99929105, 0.77904286]])

> Extract all the data >0.5

In [97]:
arr > 0.5

array([[ True,  True, False, False,  True],
       [False,  True,  True,  True,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True,  True,  True]])

In [96]:

arr[arr > 0.5]

array([0.65606435, 0.67818371, 0.5904563 , 0.73470839, 0.80892093,
       0.98021567, 0.72487239, 0.57043771, 0.55017421, 0.79097872,
       0.52457782, 0.61419716, 0.73371306, 0.99929105, 0.77904286])

In [103]:
arr

array([[0.65606435, 0.67818371, 0.44047451, 0.15464058, 0.5904563 ],
       [0.1836203 , 0.73470839, 0.80892093, 0.98021567, 0.72487239],
       [0.57043771, 0.55017421, 0.46563048, 0.79097872, 0.11013741],
       [0.52457782, 0.61419716, 0.73371306, 0.99929105, 0.77904286]])

In [104]:
# 2th column's 2 middle rows
arr[[1,2],[2]]

array([0.80892093, 0.46563048])

In [107]:
arr = np.random.rand(8,5)

In [108]:
arr

array([[0.15552663, 0.49828828, 0.57545401, 0.13391372, 0.96203398],
       [0.69108387, 0.36215328, 0.91712382, 0.96187827, 0.24114236],
       [0.98848885, 0.24034792, 0.55390925, 0.91338326, 0.92886133],
       [0.85872883, 0.68831501, 0.54213997, 0.30721017, 0.01213139],
       [0.91539529, 0.15326852, 0.30351656, 0.70330253, 0.15430601],
       [0.31932888, 0.93097315, 0.54656119, 0.17022056, 0.70480379],
       [0.19737623, 0.88878612, 0.71742698, 0.18783576, 0.47915648],
       [0.24383174, 0.52391921, 0.35396172, 0.47336928, 0.29867065]])

In [114]:
arr[1:8,0:3]

array([[0.69108387, 0.36215328, 0.91712382],
       [0.98848885, 0.24034792, 0.55390925],
       [0.85872883, 0.68831501, 0.54213997],
       [0.91539529, 0.15326852, 0.30351656],
       [0.31932888, 0.93097315, 0.54656119],
       [0.19737623, 0.88878612, 0.71742698],
       [0.24383174, 0.52391921, 0.35396172]])

In [115]:
arr[[1,2,3,4,5,6,7],[0,1,2]]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (7,) (3,) 

In [117]:
a2 = arr[1:8,[0,1,2]]

In [118]:
a2

array([[0.69108387, 0.36215328, 0.91712382],
       [0.98848885, 0.24034792, 0.55390925],
       [0.85872883, 0.68831501, 0.54213997],
       [0.91539529, 0.15326852, 0.30351656],
       [0.31932888, 0.93097315, 0.54656119],
       [0.19737623, 0.88878612, 0.71742698],
       [0.24383174, 0.52391921, 0.35396172]])

In [119]:
a2[0][0] = 1234

In [120]:
a2

array([[1.23400000e+03, 3.62153280e-01, 9.17123820e-01],
       [9.88488852e-01, 2.40347917e-01, 5.53909253e-01],
       [8.58728832e-01, 6.88315010e-01, 5.42139965e-01],
       [9.15395292e-01, 1.53268515e-01, 3.03516557e-01],
       [3.19328876e-01, 9.30973147e-01, 5.46561188e-01],
       [1.97376232e-01, 8.88786117e-01, 7.17426977e-01],
       [2.43831740e-01, 5.23919206e-01, 3.53961715e-01]])

In [122]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])

In [123]:
# This is element wise multiplication, not matrix multiplication
a*b

array([[ 2,  6],
       [12, 20]])

In [125]:
# Matrix Multiplication : 
# Matrix multiplication represented by '@'
a@b

array([[10, 13],
       [22, 29]])

In [126]:
# Python core gives Zero Division Exception
# Numpy doesn't do this, it gives infiniy.
a/0

C:\Users\soman\AppData\Local\Temp/ipykernel_19232/4102073204.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a/0


array([[inf, inf],
       [inf, inf]])

### NOte : This functions will be useful not in machine learning but deep learning, computer vision, nlp, etc use cases.

In [ ]:
# 16th March
